AWSTemplateFormatVersion: '2010-09-09'

Resources:

  PublicRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue VPCId

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: PublicRT
    Properties:
      RouteTableId: !Ref PublicRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !ImportValue IGWId

  PrivateRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue VPCId

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRT
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !ImportValue NATId