AWSTemplateFormatVersion: '2010-09-09'

Resources:
  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 SG
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !ImportValue ALBSG

Outputs:
  EC2SG:
    Value: !Ref EC2SG
    Export:
      Name: EC2SG