AWSTemplateFormatVersion: '2010-09-09'

Resources:
  RDSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS SG
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !ImportValue EC2SG

Outputs:
  RDSSG:
    Value: !Ref RDSSG
    Export:
      Name: RDSSG