TargetGroup:
  Type: AWS::ElasticLoadBalancingV2::TargetGroup
  Properties:
    Port: 80
    Protocol: HTTP
    VpcId: !ImportValue VPCId
    HealthCheckPath: /
    HealthCheckIntervalSeconds: 30
