AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DBInstanceClass:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true

Resources:

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnets for DB
      SubnetIds: !Split [",", !ImportValue PrivateSubnets]

  DB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: 20
      MasterUsername: admin
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !ImportValue RDSSG
